spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: passpwrd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level: # 日志级别设置
    root: warn
    com.ftj: info
  file: /logs/blogs/blog-prod.log #日志大小超过10M，默认切分 我这里部署Linux
server:
  port: 8081